
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
        tableUpdate();
        txtittle.requestFocus();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtittle = new javax.swing.JTextField();
        Cgenre = new javax.swing.JComboBox<>();
        txAuthor = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        titleTx = new javax.swing.JTextField();
        genreTx = new javax.swing.JTextField();
        authorTx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txPubisher = new javax.swing.JTextField();
        showAll = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 42));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Title:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Genre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Publisher:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));
        getContentPane().add(txtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, -1));

        Cgenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romance", "Crime and Thriller", "Sci-fi", "Biography", "Mystery" }));
        getContentPane().add(Cgenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, -1));
        getContentPane().add(txAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 110, -1));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        getContentPane().add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 79, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 79, -1));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tittle:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Genre:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Author:");

        titleTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleTxKeyReleased(evt);
            }
        });

        genreTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genreTxKeyReleased(evt);
            }
        });

        authorTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                authorTxKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Search by:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleTx, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(genreTx, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(authorTx)))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(titleTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(authorTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookID", "Tittle", "Genre ", "Author ", "Publisher"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 490, 156));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\home (1).png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 445, 70, 50));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("© Universiteti Europian i Tiranes");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Developed by Edionis Boboçi.");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\logo-uet-PNG.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 890, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Author:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, -1));
        getContentPane().add(txPubisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, -1));

        showAll.setBackground(new java.awt.Color(0, 0, 0,80));
        showAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showAll.setForeground(new java.awt.Color(255, 255, 255));
        showAll.setText("Show All");
        showAll.setMaximumSize(new java.awt.Dimension(103, 33));
        showAll.setMinimumSize(new java.awt.Dimension(103, 33));
        showAll.setPreferredSize(new java.awt.Dimension(103, 33));
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });
        getContentPane().add(showAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 110, 50));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\imageedit_1_9192635872.gif")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LandingPage menu=new LandingPage();
              menu.setVisible(true);
              setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed
PreparedStatement insert;
    private void tableUpdate() {
        int tb;
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from books");
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                   v1.add(rs.getString("bookId"));
                   v1.add(rs.getString("bookName"));
                   v1.add(rs.getString("bookGenre"));
                   v1.add(rs.getString("bookAuthor"));
                   v1.add(rs.getString("publisher"));
                     
               }
               Df.addRow(v1);
               
           }
        }
        
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    
    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();

        int sIndex=jTable1.getSelectedRow();
        try{
         
        String title=txtittle.getText();
        String author=txAuthor.getText(); 
        String publisher=txPubisher.getText();
         int id=Integer.parseInt(Df.getValueAt(sIndex, 0).toString());
         int dialogResult=JOptionPane.showConfirmDialog(null, "Do you want to delete data","Warning",JOptionPane.YES_NO_OPTION);
         if(dialogResult==JOptionPane.YES_OPTION){
         
          //hap lidhjen
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
          insert=con.prepareStatement("delete from books where bookId=?");
        
          insert.setInt(1,id);
          insert.executeUpdate();
          JOptionPane.showMessageDialog(this,"Data deleted");
         }
        
          
       
          tableUpdate();
        txtittle.setText("");
        Cgenre.setSelectedIndex(0);
        txAuthor.setText("");     
        txPubisher.setText("");
        txtittle.requestFocus();
      }
      
      catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          
      }

    }//GEN-LAST:event_delBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        txtittle.setText("");
        Cgenre.setSelectedIndex(0);
        txAuthor.setText("");     
       txPubisher.setText("");
    }//GEN-LAST:event_cancelBtnActionPerformed

    
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String title=txtittle.getText();
        String author=txAuthor.getText();
        String publisher=txPubisher.getText();
         try{
          //hap lidhjen
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
          insert=con.prepareStatement("insert into books(bookName,bookGenre,bookAuthor,publisher)values(?,?,?,?)");
          insert.setString(1, title);
          String genre=Cgenre.getSelectedItem().toString();
          insert.setString(2,genre);
          insert.setString(3,author);
          insert.setString(4,publisher);
          insert.executeUpdate();
          
          JOptionPane.showMessageDialog(this,"Book added!");
           tableUpdate();
        txtittle.setText("");
        Cgenre.setSelectedIndex(0);
        txAuthor.setText("");     
        txPubisher.setText("");
        txtittle.requestFocus();
      }
      
      catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          
      }
                                         
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();

        int sIndex=jTable1.getSelectedRow();
     try{
         
        String title=txtittle.getText();
        String author=txAuthor.getText();
        String publisher=txPubisher.getText();
         int id=Integer.parseInt(Df.getValueAt(sIndex, 0).toString());
         
         
         
          //hap lidhjen
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
          insert=con.prepareStatement("update books set bookName=?,bookGenre=?,bookAuthor=?,publisher=? where bookId=?");
          insert.setString(1, title);
          String genre=Cgenre.getSelectedItem().toString();
          insert.setString(2,genre);
          insert.setString(3,author);
          insert.setString(4,publisher);
          insert.setInt(5,id);
          insert.executeUpdate();
          
          JOptionPane.showMessageDialog(this,"Data updated");
           tableUpdate();
        txtittle.setText("");
        Cgenre.setSelectedIndex(0);
        txAuthor.setText("");     
        txPubisher.setText("");
        txtittle.requestFocus();
        
      }
      
      catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          
      }
     
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();

        int sIndex=jTable1.getSelectedRow();
        txtittle.setText(Df.getValueAt(sIndex, 1).toString());
        Cgenre.setSelectedItem(Df.getValueAt(sIndex, 2).toString());
        txAuthor.setText(Df.getValueAt(sIndex, 3).toString());
        txPubisher.setText(Df.getValueAt(sIndex, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void titleTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleTxKeyReleased
        // TODO add your handling code here:
        
         int tb;
    String search=titleTx.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from books where bookName=?");
           insert.setString(1,search);
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                   v1.add(rs.getString("bookId"));
                   v1.add(rs.getString("bookName"));
                   v1.add(rs.getString("bookGenre"));
                   v1.add(rs.getString("bookAuthor"));
                   v1.add(rs.getString("publisher"));
                     
               }
               Df.addRow(v1);
               
           }
           
        }
        
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_titleTxKeyReleased

    private void genreTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genreTxKeyReleased
        // TODO add your handling code here:
             int tb;
    String search=genreTx.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from books where bookGenre=?");
           insert.setString(1,search);
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                   v1.add(rs.getString("bookId"));
                   v1.add(rs.getString("bookName"));
                   v1.add(rs.getString("bookGenre"));
                   v1.add(rs.getString("bookAuthor"));
                   v1.add(rs.getString("publisher"));
                     
               }
               Df.addRow(v1);
               
           }
           
        }
        
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_genreTxKeyReleased

    private void authorTxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorTxKeyReleased
        // TODO add your handling code here:
                int tb;
    String search=authorTx.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from books where bookAuthor=?");
           insert.setString(1,search);
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                   v1.add(rs.getString("bookId"));
                   v1.add(rs.getString("bookName"));
                   v1.add(rs.getString("bookGenre"));
                   v1.add(rs.getString("bookAuthor"));
                   v1.add(rs.getString("publisher"));
                     
               }
               Df.addRow(v1);
               
           }
           
        }
        
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_authorTxKeyReleased

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.mysql.jdbc.Driver");            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
            
            tableUpdate();
             txtittle.setText("");
             Cgenre.setSelectedIndex(0);
             txAuthor.setText("");     
             txPubisher.setText("");
             txtittle.requestFocus();
             
            
        }
             catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_showAllActionPerformed

    
      //------------------------------------------------------------------------------------------------
    //-----------------------------------Get data selected from table---------------------------------
    //------------------------------------------------------------------------------------------------
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cgenre;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField authorTx;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField genreTx;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showAll;
    private javax.swing.JTextField titleTx;
    private javax.swing.JTextField txAuthor;
    private javax.swing.JTextField txPubisher;
    private javax.swing.JTextField txtittle;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
