
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Borrowed extends javax.swing.JFrame {

    /**
     * Creates new form Borrowed
     */
    public Borrowed() {
        initComponents();
        tableUpdate();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/3-getWidth()/3,size.height/3-getHeight()/3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        durationTx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookTx = new javax.swing.JTextField();
        empTx = new javax.swing.JTextField();
        studentTx = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        showAll = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookSearch = new javax.swing.JTextField();
        empSearch = new javax.swing.JTextField();
        studentSearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Borrowed books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrow ID", "Duration", "Book ID", "Emloyee", "Student ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 195));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Duration:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(durationTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Book ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Employee ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Student ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        bookTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTxActionPerformed(evt);
            }
        });
        getContentPane().add(bookTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, -1));
        getContentPane().add(empTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, -1));
        getContentPane().add(studentTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 100, -1));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\home (1).png")); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 78, 51));

        showAll.setBackground(new java.awt.Color(0, 0, 0,80));
        showAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showAll.setForeground(new java.awt.Color(240, 240, 240));
        showAll.setText("Show All");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });
        getContentPane().add(showAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Search by:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Book ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Employee ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("Student ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        bookSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bookSearchKeyReleased(evt);
            }
        });
        jPanel1.add(bookSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 90, -1));

        empSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empSearchKeyReleased(evt);
            }
        });
        jPanel1.add(empSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 90, -1));

        studentSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentSearchKeyReleased(evt);
            }
        });
        jPanel1.add(studentSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 280, 140));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\imageedit_1_9828355985.gif")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 830, 470));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\logo-uet-PNG.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("© Universiteti Europian i Tiranes");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Developed by Edionis Boboçi.");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 840, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookTxActionPerformed
PreparedStatement insert;
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         String duration=durationTx.getText();
         try{
          //hap lidhjen
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
          insert=con.prepareStatement("insert into borrowed (duration,bookId ,empId,ID)values(?,?,?,?)");
          insert.setString(1,duration);
          int bookId=Integer.parseInt(bookTx.getText());
          insert.setInt(2,bookId);
          int empId=Integer.parseInt(empTx.getText());
          insert.setInt(3,empId);
          int ID=Integer.parseInt(studentTx.getText());
          insert.setInt(4,ID);
          insert.executeUpdate();
          
          JOptionPane.showMessageDialog(this,"Employee added!");
           tableUpdate();
        durationTx.setText("");
        bookTx.setText("");     
        empTx.setText("");
        studentTx.setText("");
        durationTx.requestFocus();
      }
      
      catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          
      }
    }//GEN-LAST:event_addBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        LandingPage menu=new LandingPage();
              menu.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        durationTx.setText("");
        bookTx.setText("");     
        empTx.setText("");
        studentTx.setText("");
        durationTx.requestFocus();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();

        int sIndex=jTable1.getSelectedRow();
        try{
         
         String duration=durationTx.getText();
         int id=Integer.parseInt(Df.getValueAt(sIndex, 0).toString());
         int dialogResult=JOptionPane.showConfirmDialog(null, "Do you want to delete data","Warning",JOptionPane.YES_NO_OPTION);
         if(dialogResult==JOptionPane.YES_OPTION){
         
          //hap lidhjen
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
          insert=con.prepareStatement("delete from borrowed where idBorrowed=?");
        
          insert.setInt(1,id);
          insert.executeUpdate();
          JOptionPane.showMessageDialog(this,"Data deleted");
         }
         
        
          
       
          tableUpdate();
        durationTx.setText("");
        bookTx.setText("");     
        empTx.setText("");
        studentTx.setText("");
        durationTx.requestFocus();
      }
      
      catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();

        int sIndex=jTable1.getSelectedRow();
        durationTx.setText(Df.getValueAt(sIndex, 1).toString());
        bookTx.setText(Df.getValueAt(sIndex, 2).toString());
        empTx.setText(Df.getValueAt(sIndex, 3).toString());
        studentTx.setText(Df.getValueAt(sIndex, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();

        int sIndex=jTable1.getSelectedRow();
     try{
         
       
         int id=Integer.parseInt(Df.getValueAt(sIndex, 0).toString());
         String duration=durationTx.getText();
        
          //hap lidhjen
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
          insert=con.prepareStatement("update borrowed set duration=?,bookId=?,empId=?,ID=? where idBorrowed=?");
          insert.setString(1,duration);
          int bookId=Integer.parseInt(bookTx.getText());
          insert.setInt(2,bookId);
          int empId=Integer.parseInt(empTx.getText());
          insert.setInt(3,empId);
          int ID=Integer.parseInt(studentTx.getText());
          insert.setInt(4,ID);
          insert.setInt(5,id);
          insert.executeUpdate();
          
          
          JOptionPane.showMessageDialog(this,"Data updated");
        tableUpdate();
        durationTx.setText("");
        bookTx.setText("");     
        empTx.setText("");
        studentTx.setText("");
        durationTx.requestFocus();
      }
      
      catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          
      }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.mysql.jdbc.Driver");            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
            
            tableUpdate();
         durationTx.setText("");
        bookTx.setText("");     
        empTx.setText("");
        studentTx.setText("");
        durationTx.requestFocus();
            
        }
             catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_showAllActionPerformed

    private void bookSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookSearchKeyReleased
        // TODO add your handling code here:
         int tb;
    String search=bookSearch.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from borrowed where bookId=?");
           insert.setString(1,search);
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                  v1.add(rs.getString("idBorrowed"));
                   v1.add(rs.getString("duration"));
                   v1.add(rs.getInt("bookId"));
                   v1.add(rs.getString("empId"));
                   v1.add(rs.getString("Id"));
                     
                     
               }
               Df.addRow(v1);
               
           }
           
        }
        
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
       
    }//GEN-LAST:event_bookSearchKeyReleased

    private void empSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empSearchKeyReleased
        // TODO add your handling code here:
               int tb;
    String search=empSearch.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from borrowed where empId=?");
           insert.setString(1,search);
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                  v1.add(rs.getString("idBorrowed"));
                   v1.add(rs.getString("duration"));
                   v1.add(rs.getInt("bookId"));
                   v1.add(rs.getString("empId"));
                   v1.add(rs.getString("Id"));
                     
                     
               }
               Df.addRow(v1);
               
           }
           
        }
        
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_empSearchKeyReleased

    private void studentSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentSearchKeyReleased
        // TODO add your handling code here:
               int tb;
    String search=studentSearch.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from borrowed where ID=?");
           insert.setString(1,search);
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                  v1.add(rs.getString("idBorrowed"));
                   v1.add(rs.getString("duration"));
                   v1.add(rs.getInt("bookId"));
                   v1.add(rs.getString("empId"));
                   v1.add(rs.getString("Id"));
                     
                     
               }
               Df.addRow(v1);
               
           }
           
        }
        
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_studentSearchKeyReleased

    
         private void tableUpdate() {
        int tb;
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           insert=con.prepareStatement("select * from borrowed");
           ResultSet rs= insert.executeQuery();
           ResultSetMetaData Rss=rs.getMetaData();
           tb=Rss.getColumnCount();
           DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
           Df.setRowCount(0);
           
           while(rs.next()){
               Vector v1=new Vector();
               
               for(int a=1; a<=tb; a++)
               {
                   v1.add(rs.getString("idBorrowed"));
                   v1.add(rs.getString("duration"));
                   v1.add(rs.getInt("bookId"));
                   v1.add(rs.getString("empId"));
                   v1.add(rs.getString("Id"));
                     
               }
               Df.addRow(v1);
               
           }
        }
        
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
     }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrowed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField bookSearch;
    private javax.swing.JTextField bookTx;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField durationTx;
    private javax.swing.JTextField empSearch;
    private javax.swing.JTextField empTx;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showAll;
    private javax.swing.JTextField studentSearch;
    private javax.swing.JTextField studentTx;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
